### ISSUE TITLE
Улучшить видимость лесенок

### ISSUE THREAD

**Issue by Ori-Lama** [Silvman/ponydays#25]
Возможно это просто дело вкуса, но отсутствие у комментария левой границы затрудняет иногда быстрое определение ветки в которой он находится. Приходится чаще нажимать на стрелку перехода к родительскому комментарию.

**Comment by lunavod** [comment]
Думаю, тут таки стоит что-то сделать. Нужно только определиться, что именно - если выделять все комментарии цветом, это выглядит довольно фигово.

**Comment by Ori-Lama** [comment]
Я сам не дизайнер, так что вопросы по дизайну.. эт сложна )

**Comment by lunavod** [comment]
Я тоже не особо дизайнер, мне тоже сложно. :D
В принципе, можно как на хабре сделать, например...

**Comment by Ori-Lama** [comment]
Да, на хабре неплохо..

**Comment by JSkrat** [comment]
полосочки вертикальной слева будет вполне достаточно. А на хабре мышу наводить обязательно нужно, это немного напряжно

**Comment by lunavod** [comment]
Полосочка слева будет совершенно в дизайн не вписываться. А точки можно сделать немного различимыми без навода мышки.

**Comment by JSkrat** [comment]
http://i.imgur.com/zGdbrUv.png
во, вот эту полосочку чуть ярче-толще сделать и норм буит, ящитаю

**Comment by lunavod** [comment]
@Ori-Lama 
Как думаешь?

**Comment by JSkrat** [comment]
(только чтобы и на своих комментариях она была видна, да

**Comment by Ori-Lama** [comment]
Думаю, что надо пробовать. Я тоже думал о какой-то тонкой ограничительной линии слева.

**Comment by lunavod** [comment]
Стоп, а Джей предлагает таки сделать линию слева? Я думал он предлагает сделать ярче линию сверху.

**Comment by Ori-Lama** [comment]
А я не понял.

**Comment by JSkrat** [comment]
ну на скрине линия горизонтальная. Хотя как по мне и вертикальная, не доходящая до краёв блока и со скруглёнными концами шириной пикселей 4 смотрелась бы хорошо. Ещё и цветами линий можно выделять комментарии вместо цветов фона

**Comment by lunavod** [comment]
В новом дизайне все норм.
